### ISSUE TITLE
Seleção de Favoritos - Na versão web, ao tentar marcar um favorito, a lista não é atualizada na home

### ISSUE THREAD

**Issue by garymsilva** [prodest/es-na-palma-da-mao-mobile-vnext#49]
## Comportamento esperado

Marcar o favorito quando clicar no ícone e refletir as mudanças na Home.

## Comportamento atual

Ao rodar o app com `ionic serve` ou, depois de fazer o build, executar com `npm run serve`, o favorito não é salvo.

## Passos para reproduzir

Descreva aqui um passo a passo para reproduzir o problema. Links e imagens são bem vindos.
1. Configurar o ambiente de desenvolvimento local
2. Executar com `ionic serve`
3. Navegar até a seleção de favoritos
4. Tentar marcar um item qualquer

**Comment by vizeke** [comment]
@garymsilva favor verificar se esse erro continua com a versão atualizada do app. Com node 10 e cordova 9.

**Comment by garymsilva** [comment]
Testado @vizeke . Funcionando no Release, no `npm run serve` e no `ionic serve`.

**Comment by vizeke** [comment]
thanks
