### ISSUE TITLE
Oportunidades (DT) - Botão "Lista de Classificados" sobrepõe a lista de anexos do concurso.

### ISSUE THREAD

**Issue by garymsilva** [prodest/es-na-palma-da-mao-mobile-vnext#51]
## Comportamento esperado

Ao abrir um concurso, o botão ficar depois da lista.

## Comportamento atual

O botão sobrepõe a lista de anexos, impedindo a visualização dos últimos.

## Passos para reproduzir

Descreva aqui um passo a passo para reproduzir o problema. Links e imagens são bem vindos.
1. Acessar o módulo Oportunidades > Designação Temporária
2. Procurar um concurso com muitos anexos
3. O botão Lista de Classificados irá estar sobre os itens da lista.

**Comment by vizeke** [comment]
corrigido.
